<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
قشر کتاب‌خوان
</font>
</h1>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
در این تمرین برای کمک به قشر کتابخوان می‌خواهیم به تحلیل داده‌های سایت <i>goodreads</i> بپردازیم و اطلاعات جالب و کاربردی‌ای را از آن استخراج کنیم.
</font>
</p>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import os
os.chdir('/content/drive/MyDrive/ML/DataMining')

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
مجموعه‌داده
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
اطلاعات کتاب‌ها در فایل <code>books_db.csv</code>،‌ نویسندگان در فایل <code>authors.csv</code>، ناشران در فایل <code>publisher.csv</code> و زبان‌ها در فایل <code>language.csv</code> قرار گرفته است. به‌کمک پانداز هرکدام از این فایل‌ها را خوانده و در متغیر متناظر آن ذخیره کنید.
</font>
</p>

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('/content/drive/MyDrive/ML/DataMining/قشر کتابخوان/books_db.csv')
authors = pd.read_csv('/content/drive/MyDrive/ML/DataMining/قشر کتابخوان/authors.csv')
language = pd.read_csv('/content/drive/MyDrive/ML/DataMining/قشر کتابخوان/language.csv')
publisher = pd.read_csv('/content/drive/MyDrive/ML/DataMining/قشر کتابخوان/publisher.csv')

df.head()

,bookID,title,average_rating,isbn,isbn13,num_pages,ratings_count,text_reviews_count,publication_date,author_id,lang_id,publisher_id
0,1,Harry Potter and the Half-Blood Prince (Harry ...,4.57,439785960,9.780440e+12,652,2095690,27591,9/16/2006,0,0,0
1,2,Harry Potter and the Order of the Phoenix (Har...,4.49,439358078,9.780440e+12,870,2153167,29221,9/1/2004,0,0,0
2,4,Harry Potter and the Chamber of Secrets (Harry...,4.42,439554896,9.780440e+12,352,6333,244,11/1/2003,0,0,1
3,5,Harry Potter and the Prisoner of Azkaban (Harr...,4.56,043965548X,9.780440e+12,435,2339585,36325,5/1/2004,0,0,0
4,8,Harry Potter Boxed Set Books 1-5 (Harry Potte...,4.78,439682584,9.780440e+12,2690,41428,164,9/13/2004,0,0,1

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
قسمت اول
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
همان‌طور که مشاهده می‌کنید در مجموعه‌داده‌ی اصلی (کتاب‌ها)، مقادیر سه ستون <code>lang_id</code>، <code>author_id</code> و <code>publisher_id</code> تنها به‌صورت آیدی (<code>id</code>) هستند. این آیدی‌ها با شماره‌ی نمایه‌ها در سایر دیتافریم‌ها متناظر هستند. در این قسمت قصد داریم تا طبق این نمایه‌ها،‌ اطلاعات کامل‌شان را از دیتافریم مربوطه استخراج کرده و به دیتافریم <code>df</code> اضافه کنیم. بنابراین سه دیتافریم <code>authors</code>، <code>language</code> و <code>publisher</code> را به‌شکل مناسبی با دیتافریم <code>df</code> ادغام (<code>merge</code>) کنید.
</font>
</p>

In [ ]:
# To-Do: about 3 lines of code
df = pd.merge(df , authors , left_on = 'author_id' , right_index= True)
df = pd.merge(df , language , left_on = 'lang_id' , right_index= True)
df = pd.merge(df , publisher , left_on = 'publisher_id' , right_index= True)
df.head()

,bookID,title,average_rating,isbn,isbn13,num_pages,ratings_count,text_reviews_count,publication_date,author_id,lang_id,publisher_id,name_x,code,name_y
0,1,Harry Potter and the Half-Blood Prince (Harry ...,4.57,439785960,9.780440e+12,652,2095690,27591,9/16/2006,0,0,0,J.K. Rowling,eng,Scholastic Inc.
1,2,Harry Potter and the Order of the Phoenix (Har...,4.49,439358078,9.780440e+12,870,2153167,29221,9/1/2004,0,0,0,J.K. Rowling,eng,Scholastic Inc.
2,4,Harry Potter and the Chamber of Secrets (Harry...,4.42,439554896,9.780440e+12,352,6333,244,11/1/2003,0,0,1,J.K. Rowling,eng,Scholastic
3,5,Harry Potter and the Prisoner of Azkaban (Harr...,4.56,043965548X,9.780440e+12,435,2339585,36325,5/1/2004,0,0,0,J.K. Rowling,eng,Scholastic Inc.
4,8,Harry Potter Boxed Set Books 1-5 (Harry Potte...,4.78,439682584,9.780440e+12,2690,41428,164,9/13/2004,0,0,1,J.K. Rowling,eng,Scholastic

In [ ]:
# Renaming columns
df = df.rename(columns={'name_x': 'author_name', 'name_y': 'publisher_name', 'code': 'language'})

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
حال که تمام مقادیر اضافه شده‌اند، نیازی به سه ستون <code>id</code> که به‌عنوان کلید استفاده کردیم نداریم. پس آن‌ها را با استفاده از دستور <code>drop</code> حذف می‌کنیم.
        در درسنامه‌های بعدی نحوه‌ی کار با این دستور را یاد خواهید گرفت.    
</font>
</p>

In [ ]:
df.drop(columns = ['author_id', 'lang_id', 'publisher_id'], inplace = True)

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
قسمت دوم
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
حال نام ستون‌های دیتافریم را به‌گونه‌ای تغییر دهید که به‌ترتیب از چپ به راست برابر نام‌های زیر باشد:
<ul>
<li><code>bookID</code></li>
<li><code>title</code></li>
<li><code>average_rating</code></li>
<li><code>isbn</code></li>
<li><code>isbn13</code></li>
<li><code>num_pages</code></li>
<li><code>ratings_count</code></li>
<li><code>text_reviews_count</code></li>
<li><code>publication_date</code></li>
<li><code>author</code></li>
<li><code>lang</code></li>
<li><code>publisher</code></li>
</font>
</p>

In [ ]:
df.columns

Index(['bookID', 'title', 'average_rating', 'isbn', 'isbn13', 'num_pages',
       'ratings_count', 'text_reviews_count', 'publication_date',
       'author_name', 'language', 'publisher_name'],
      dtype='object')

In [ ]:
df = df.rename(columns={
    'author_name': 'author',
    'language': 'lang',
    'publisher_name': 'publisher'
})

In [ ]:
df.columns

Index(['bookID', 'title', 'average_rating', 'isbn', 'isbn13', 'num_pages',
       'ratings_count', 'text_reviews_count', 'publication_date', 'author',
       'lang', 'publisher'],
      dtype='object')

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
قسمت سوم
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
اکنون میانگین امتیاز کتاب‌های هر انتشاراتی را محاسبه کرده و حاصل را در متغیر <code>publisher_rating</code> ذخیره کنید.
</font>
</p>

In [ ]:
# compute mean of rates with each publisher by average_rating
publisher_rating = df.groupby('publisher')['average_rating'].mean()
publisher_rating

publisher
18-Oct                           3.650000
1st Book Library                 3.580000
1st World Library                4.180000
A & C Black (Childrens books)    4.400000
A Harvest Book/Harcourt  Inc.    4.070000
                                   ...
聯經出版事業股份有限公司                     4.400000
英文漢聲出版股份有限公司                     4.220000
角川書店 (Kadokawa Shoten)           3.815000
講談社                              4.283333
集英社                              4.237500
Name: average_rating, Length: 2290, dtype: float64

In [ ]:
publisher_rating.sort_values(ascending=False).head(10)

publisher
Square One Publishers              5.0
Vantage Press                      5.0
Y Lolfa                            5.0
Schirmer Mosel                     5.0
University Press of New England    5.0
T&T Clark Int'l                    5.0
Boosey & Hawkes Inc                5.0
Chartwell Books                    5.0
Texas A&M University Press         5.0
Raintree                           5.0
Name: average_rating, dtype: float64

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
قسمت چهارم
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
در این قسمت ابتدا ستونی با نام <code>num_pages_grp</code> به دیتافریم اضافه کنید که در آن تعداد صفحات کتاب را به‌صورت بازه‌های زیر نشان دهد:
</font>
</p>

<center>
<div dir=rtl style="direction: rtl;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>

| <b>مقدار</b> | <b>توضیح</b> |
| :---: | :---: |
| <code dir=ltr><250</code> | کمتر از ۲۵۰ صفحه |
| <code dir=ltr>250-499</code> | از ۲۵۰ تا ۴۹۹ صفحه |
| <code dir=ltr>500-749</code> | از ۵۰۰ تا ۷۴۹ صفحه |
| <code dir=ltr>750-999</code> | از ۷۵۰ تا ۹۹۹ صفحه |
| <code dir=ltr>>=1000</code> | بیشتر یا مساوی ۱۰۰۰ صفحه |

</font>
</div>
</center>


<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
<span style="color:green"><b>راهنمایی :</b></span>
 برای این کار می‌توانید از تابع <code>np.select</code> استفاده کنید.
</font>
</p>

In [ ]:
conditions = [
    (df['num_pages'] < 250),
    (df['num_pages'] >= 250) & (df['num_pages'] < 500),
    (df['num_pages'] >= 500) & (df['num_pages'] < 750),
    (df['num_pages'] >= 750) & (df['num_pages'] < 1000),
    (df['num_pages'] >= 1000)
]

choices = ['<250', '250-499', '500-749', '750-999', '>=1000']
df['num_pages_grp'] = np.select(conditions, choices, default='unknown')
df['num_pages_grp']

0        500-749
1        750-999
2        250-499
3        250-499
4         >=1000
          ...
11119    500-749
11120    500-749
11121    250-499
11122    250-499
11123    250-499
Name: num_pages_grp, Length: 11124, dtype: object

In [ ]:
df['num_pages_grp'].value_counts()

num_pages_grp
250-499    5106
<250       4273
500-749    1185
750-999     343
>=1000      217
Name: count, dtype: int64


<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
حال می‌خواهیم بدانیم هر نویسنده چند کتاب در هرکدام از این بازه‌ها نوشته است. یعنی حاصل باید چیزی شبیه به جدول زیر باشد:

</font>
</p>

A.B. Yehoshua          250-499          1
                       500-749          1
A.D.P. Briggs          250-499          1
A.E. Cunningham        <250             1
A.J. Jacobs            250-499          1

In [ ]:
author_page = df.groupby(['author', 'num_pages_grp']).size()
author_page

author                 num_pages_grp
A.B. Yehoshua          250-499          1
                       500-749          1
A.D.P. Briggs          250-499          1
A.E. Cunningham        <250             1
A.J. Jacobs            250-499          1
                                       ..
bell hooks             <250             5
Åsne Seierstad         250-499          3
Émile Zola             250-499          6
                       500-749          3
Éric-Emmanuel Schmitt  <250             1
Length: 5547, dtype: int64


<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
<b>سلول زیر را حتما اجرا کنید</b> تا نام دیتاسری <code>aurthor_page</code> در روند داوری این بخش تاثیری نداشته باشد :
</font>
</p>

In [ ]:
author_page.name = None

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
<b>سلول جواب‌ساز</b>
</font>
</h2>


<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
    برای ساخته‌شدن فایل <code>result.zip</code> سلول زیر را اجرا کنید. توجه داشته باشید که پیش از اجرای سلول زیر تغییرات اعمال شده در نت‌بوک را ذخیره کرده باشید (<code>ctrl+s</code>) تا در صورت نیاز به پشتیبانی امکان بررسی کد شما وجود داشته باشد.
</font>
</p>

In [ ]:
import zlib
import zipfile

df.to_csv('books_result.csv', index=False)
publisher_rating.to_csv('publisher_rating.csv', index=True)
author_page.to_csv("author_page.csv", index=True)

def compress(file_names):
    print("File Paths:")
    print(file_names)
    compression = zipfile.ZIP_DEFLATED
    with zipfile.ZipFile("result.zip", mode="w") as zf:
        for file_name in file_names:
            zf.write('./' + file_name, file_name, compress_type=compression)

file_names = ["books_result.csv", "publisher_rating.csv", "author_page.csv", "book_readers.ipynb"]
compress(file_names)

File Paths:
['books_result.csv', 'publisher_rating.csv', 'author_page.csv', 'book_readers.ipynb']


<br />
<div dir=rtl id="start" style="direction:rtl;line-height:200%;">
	<font face="vazir" size
        سلاموری ارسال کنید.
  </p>
</div>