<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
پیش‌پردازش
</font>
</h1>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    در نخستین گام از پروژه‌ی نهایی یک سری مراحل پیش‌پردازش را بر روی داده‌ها اعمال خواهید کرد تا مجموعه‌داده‌ی باکیفیت‌تری را برای مراحل بعدی پروژه آماده کنید. علاوه بر این طبق همین مراحل به چند پرسش تحلیلی هم پاسخ خواهید داد.
</font>
</p>

   
<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
کتابخانه‌ها
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
       ابتدا کتابخانه‌های مورد نیاز خود را فرا بخوانید.
</font>
</p>

In [ ]:
# import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os
os.chdir('/content/drive/MyDrive/ML/DataMining')


<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
مجموعه‌داده
</font>
</h2>



<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    داده‌های این پروژه به‌صورت یک فایل اکسل در فایلی به نام <code>sales.xlsx</code> در اختیار شما قرار گرفته و توضیحات ستون‌های مجموعه‌داده در جدول زیر آمده است. در ابتدا این داده‌ها را در قالب یک دیتافریم بخوانید.
</font>
</p>

<center>
<div dir=rtl style="direction: rtl;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    
|ستون|توضیحات|
|:------:|:---:|
|<code>InvoiceNumber</code>|	یک شماره‌ی ۶ رقمی که به‌طور منحصر به فرد به هر فاکتور اختصاص یافته است. اگر ابتدای این شماره با حرف C شروع شود، به این معنی است که آن فاکتور لغو شده است.|
|<code>ProductCode</code>|یک شماره‌ی ۵ رقمی که به‌طور منحصر به فرد به هر نوع محصول اختصاص یافته است.|
|<code>ProductName</code>|نام محصول|
|<code>Quantity</code>|تعداد سفارش از یک نوع محصول در فاکتور|
|<code>InvoiceDate</code>|تاریخ ایجاد فاکتور|
|<code>UnitPrice</code>|قیمت یک نوع محصول به ازای یک واحد از آن|
|<code>CusotmerId</code>|یک شماره‌ی ۵ رقمی که به‌طور منحصر به فرد به هر مشتری اختصاص یافته‌ است.|
|<code>Country</code>|نام کشور محل سکونت مشتری|

</font>
</div>
</center>

In [ ]:
df = pd.read_excel('/content/drive/MyDrive/ML/DataMining/پیش‌پردازش/sales.xlsx')
df.head()

,InvoiceNumber,ProductCode,ProductName,Quantity,InvoiceDate,UnitPrice,CustomerId,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
قسمت اول    
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>    
    ابتدا فاکتورهایی که شناسه مشتری (<code>CustomerId</code>) آن‌ها موجود نیست را حذف کنید.
    این کار را بر روی یک کپی از دیتافریم به نام <code>df_no_missing_CustomerId</code> انجام دهید.
    
</font>
</p>

ردیف‌هایی که CustomerId نداشتن رو حذف کردی؛

و الان دیتافریمی داری که فقط شامل ردیف‌هاییه که شناسه مشتری دارن.

In [ ]:
df_no_missing_CustomerId = df.copy()

df_no_missing_CustomerId = df_no_missing_CustomerId.dropna(subset=['CustomerId'])

df_no_missing_CustomerId.head()

,InvoiceNumber,ProductCode,ProductName,Quantity,InvoiceDate,UnitPrice,CustomerId,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

   
<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
قسمت دوم    
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>    
سپس از بین سطر‌هایی که تمامی مقادیر آن‌ها تکراری هستند، فقط یک سطر را نگه دارید. این کار را بر روی یک کپی از دیتافریم قبل با نام <code>df_no_duplicate</code> انجام دهید.
</font>
</p>

برای حذف سطرهایی که کاملاً تکراری هستند و فقط یک نسخه از هر ردیف تکراری باقی بمونه، می‌تونی از تابع drop_duplicates() استفاده کنی.

In [ ]:
# Make a copy of the previous DataFrame
df_no_duplicate = df_no_missing_CustomerId.copy()

# Drop fully duplicated rows
df_no_duplicate = df_no_duplicate.drop_duplicates()

# Show first rows
df_no_duplicate.head()

,InvoiceNumber,ProductCode,ProductName,Quantity,InvoiceDate,UnitPrice,CustomerId,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
قسمت سوم    
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>        
همچنین سطرهایی که قیمت (<code>UnitPrice</code>) آن‌ها صفر یا عددی منفی است را نیز از مجموعه‌داده حذف کنید. به‌عبارت دیگر تنها سطرهایی که قیمت‌شان مثبت است را نگه دارید. این کار را بر روی یک کپی از دیتافریم قبل با نام <code>df_no_missing_price</code> انجام دهید.
</font>
</p>

In [ ]:
# Make a copy of the previous DataFrame
df_no_missing_price = df_no_duplicate.copy()

# Keep only rows where UnitPrice is greater than 0
df_no_missing_price = df_no_missing_price[df_no_missing_price['UnitPrice'] > 0]

# Show the first rows
df_no_missing_price.head()

,InvoiceNumber,ProductCode,ProductName,Quantity,InvoiceDate,UnitPrice,CustomerId,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
قسمت چهارم
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    اکنون طبق داده‌هایی که در مرحله‌ی قبل به دست آمدند (دیتافریم <code>df_no_missing_price</code>)، محاسبه کنید که چند درصد از کل سفارش‌ها لغو شده‌اند و عدد رُند شده‌ی آن را در متغیری به نام <code>percentage_cancelled_orders</code> ذخیره کنید. که چند درصد از کل سفارش‌ها، لغو شده‌اند.
</font>
</p>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
<span style="color:green"><b>راهنمایی ۱:</b></span>
چون ممکن است یک سفارش شامل بیش از یک محصول باشد، این احتمال وجود دارد که شناسه‌ی یک سفارش در چند ردیف تکرار شده باشد. برای محاسبه‌ی درصد سفارشات لغوشده، باید هر سفارش را تنها یک‌بار لحاظ کنید.
<br>
<span style="color:green"><b>راهنمایی ۲:</b></span>
در صورتی‌که مقدار ستون <code>InvoiceNumber</code> با حرف <code>C</code> شروع شده باشد به این معنی‌ست که آن سفارش لغو شده است.
<br>
<span style="color:green"><b>راهنمایی ۳:</b></span>
برای رُند کردن عدد از <code>round</code> استفاده کنید تا به‌عنوان مثال اگر عدد حاصل ۲۹/۸۷ درصد بود به عدد ۳۰ تبدیل شود.
<br>

</font>
</p>

In [ ]:
# Extract unique invoice numbers (each invoice only once)
unique_invoices = df_no_missing_price['InvoiceNumber'].drop_duplicates()

# Count how many of them start with 'C' (cancelled)
cancelled_count = unique_invoices[unique_invoices.astype(str).str.startswith('C')].count()

# Total number of unique invoices
total_invoices = unique_invoices.count()

# Calculate the percentage and round the result
percentage_cancelled_orders = round((cancelled_count / total_invoices) * 100)

# Show the result
percentage_cancelled_orders

19

عالیه! یعنی حدود ۱۹ درصد از سفارش‌ها لغو شدن که بر اساس داده‌هات درست محاسبه شده.

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
قسمت پنجم</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>  
در این قسمت باید به کمک دیتافریم <code>df_no_missing_price</code> پنج مشتری با بیشترین تعداد دفعات لغو سفارش را پیدا کرده و شناسه‌های آن‌ها را در قالب یک لیست (به‌ترتیب نزولی) در متغیر <code>top_cancelling_customers</code> ذخیره کنید. توجه داشته باشید که مقادیر ستون <code>CustomerId</code> از جنس عدد <code>float</code> هستند اما مقادیر لیست خروجی شما باید از جنس رشته (<code>str</code>) باشند.
</font>
</p>


<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
<span style="color:green"><b>راهنمایی ۱:</b></span>
در این قسمت هم به احتمال تکراری بودن شناسه‌ی سفارش‌ها دقت کنید. برای هر مشتری باید تعداد سفارش‌های یکتای لغوشده را محاسبه کنید.
</font>
</p>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
<span style="color:green"><b>راهنمایی ۲:</b></span>
در این قسمت دقت کنید که جنس مقادیر ستون <code>CustomerId</code> در دیتافریم <code>df_no_missing_price</code> <b>نباید تغییر کند</b> بلکه مقادیر لیست خروجی شما باید از جنس رشته (<code>str</code>) باشند. ‌می‌توانید یک کپی از دیتافریم <code>df_no_missing_price</code> بگیرید و به کمک آن لیست خروجی را بسازید.
</font>
</p>

In [ ]:
# Make a copy of the DataFrame to avoid modifying the original
df_cancel = df_no_missing_price.copy()

# Filter rows where InvoiceNumber starts with 'C' indicating cancelled orders
df_cancel = df_cancel[df_cancel['InvoiceNumber'].astype(str).str.startswith('C')]

# Drop duplicate orders based on InvoiceNumber and CustomerId to count each cancelled order once
df_cancel_unique = df_cancel.drop_duplicates(subset=['InvoiceNumber', 'CustomerId'])

# Group by CustomerId and count the number of cancelled orders per customer
cancel_counts = df_cancel_unique.groupby('CustomerId').size()

# Sort descending and take the top 5 customers with most cancelled orders
top_customers = cancel_counts.sort_values(ascending=False).head(5)

# Convert CustomerId to string type and create a list
top_cancelling_customers = top_customers.index.astype(str).tolist()

# Print the result
print(top_cancelling_customers)

['14911.0', '14527.0', '15311.0', '14156.0', '17841.0']

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
قسمت ششم
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>  
اکنون به‌عنوان آخرین مرحله‌ی پیش‌پردازش، ردیف‌های مربوط به سفارش‌های لغو شده را از دیتافریم حذف کنید. برای این کار از یک کپی از دیتافریم <code>df_no_missing_price</code> به نام <code>df_no_canceled_invoice</code> استفاده کنید و تغییرات خود را روی این دیتافریم اعمال کنید.
</font>
</p>

In [ ]:
# Make a copy of the previous DataFrame
df_no_canceled_invoice = df_no_missing_price.copy()

# Keep only rows where InvoiceNumber does NOT start with 'C' (i.e., non-canceled orders)
df_no_canceled_invoice = df_no_canceled_invoice[~df_no_canceled_invoice['InvoiceNumber'].astype(str).str.startswith('C')]

# Show first rows of the updated DataFrame
df_no_canceled_invoice.head()

,InvoiceNumber,ProductCode,ProductName,Quantity,InvoiceDate,UnitPrice,CustomerId,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom


<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>  
اکنون
دیتافریم پیش‌پردازش‌شده را در فایلی به نام <code>preprocessed_sales.csv</code> ذخیره خواهیم کرد تا در گام‌های بعدی پروژه از این مجموعه‌داده استفاده کنید.
</font>
</p>

In [ ]:
df_no_canceled_invoice.to_csv("preprocessed_sales.csv", index=False)

کد دانلود از کولب

In [ ]:
from google.colab import files
files.download('preprocessed_sales.csv')

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
قسمت هفتم
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>  
    حال شناسه‌ی سفارش‌های باقی‌مانده (حذف‌نشده) را با ساختار یک سری پانداز (<code>pd.Series</code>) در متغیر <code>remaining_invoices</code> قرار بدهید.
    <br>
    توجه کنید که تمام مقادیر موجود در متغیر <code>remaining_invoices</code> باید منحصر به فرد باشند. به عبارت بهتر، نباید در این متغیر هیچ شناسه‌ی تکراری‌ای وجود داشته باشد.
</font>
</p>

In [ ]:
# Extract unique InvoiceNumber values from the cleaned dataframe as a pandas Series
remaining_invoices = pd.Series(df_no_canceled_invoice['InvoiceNumber'].unique())
remaining_invoices

0        489434
1        489435
2        489436
3        489437
4        489438
          ...
19208    538167
19209    538168
19210    538169
19211    538170
19212    538171
Length: 19213, dtype: object

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
<b>سلول جواب‌ساز</b>
</font>
</h2>


<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
    برای ساخته‌شدن فایل <code>result.zip</code> سلول زیر را اجرا کنید. توجه داشته باشید که پیش از اجرای سلول زیر تغییرات اعمال شده در نت‌بوک را ذخیره کرده باشید (<code>ctrl+s</code>) تا در صورت نیاز به پشتیبانی امکان بررسی کد شما وجود داشته باشد.
</font>
</p>

In [ ]:
import zipfile
import joblib

joblib.dump(percentage_cancelled_orders, "percentage_cancelled_orders")
joblib.dump(top_cancelling_customers, "top_cancelling_customers")

df_no_missing_CustomerId.head(1000).to_csv("df_no_missing_CustomerId.csv", index=False)
df_no_duplicate.head(1000).to_csv("df_no_duplicate.csv", index=False)
df_no_missing_price.head(1000).to_csv("df_no_missing_price.csv", index=False)
df_no_canceled_invoice.head(1000).to_csv("df_no_canceled_invoice.csv", index=False)
remaining_invoices.to_csv("remaining_invoices.csv", index=False)

def compress(file_names):
    print("File Paths:")
    print(file_names)
    compression = zipfile.ZIP_DEFLATED
    with zipfile.ZipFile("result.zip", mode="w") as zf:
        for file_name in file_names:
            zf.write('./' + file_name, file_name, compress_type=compression)

file_names = ["df_no_canceled_invoice.csv", "df_no_missing_CustomerId.csv",
              "df_no_duplicate.csv", "df_no_missing_price.csv",
              "percentage_cancelled_orders", "top_cancelling_customers",
              "remaining_invoices.csv", "final_project_1_preprocessing.ipynb"]
compress(file_names)

File Paths:
['df_no_canceled_invoice.csv', 'df_no_missing_CustomerId.csv', 'df_no_duplicate.csv', 'df_no_missing_price.csv', 'percentage_cancelled_orders', 'top_cancelling_customers', 'remaining_invoices.csv', 'final_project_1_preprocessing.ipynb']