<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
هندوستان
</font>
</h1>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
در این تمرین به‌سراغ یک مجموعه‌داده از غذاهای هندوستان می‌رویم و بررسی می‌کنیم که هندوها تا چه حد ذائقه‌ی تندی دارند. همچنین چند مورد از دیرپزترین غذاهای‌شان را می‌یابیم.
</font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
مجموعه‌داده
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
داده‌های مرتبط با این تمرین در فایل <code>food.csv</code> قرار گرفته و شامل ستون‌های زیر است:
</font>
</p>

<center>
<div dir=rtl style="direction: rtl;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>

    
| ستون | توضیح |
| :---: | :---: |
| <code>name</code> | نام غذا |
| <code>ingredients</code>| مواد تشکیل‌دهنده‌ی غذا|
| <code>diet</code>|دارای دو مقدار <code>vegetarian</code> و <code>non vegetarian</code> است که نشان می‌دهد آیا غذا مناسب گیاه‌خواران هست یا خیر.|
| <code>prep_time</code>| زمانی که طول می‌کشد تا غذا آماده شود. این زمان شامل زمان پخت نمی‌شود. مثلاً زمان پوست کندن یا شستن مواد اولیه در این ستون لحاظ شده‌اند.|
| <code>cook_time</code>| زمان پخت یک غذا|
| <code>flavor_profile</code>| مزه‌ی غذا را نشان می‌دهد. دارای ۴ مقدار <code>spicy</code> برای غذاهای تند، <code>sweet</code> برای غذاهای شیرین، <code>bitter</code> برای غذاهای تلخ و <code>sour</code> برای غذاهای ترش است.|
| <code>course</code>| وعده‌ی اصلی، میان‌وعده، دسر یا پیش‌غذا بودن یک غذا را نشان می‌دهد.|
| <code>state</code>| ایالتی که زادگاه غذاست یا حداقل این غذا در آن‌جا معروف است.|
| <code>region</code>| منطقه‌ای که ایالت (<code>state</code>) در آن واقع شده است.|


</font>
</div>
</center>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os
os.chdir('/content/drive/MyDrive/ML/DataMining')

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/ML/DataMining/هندوستان/food.csv')
df

,name,ingredients,diet,prep_time,cook_time,flavor_profile,course,state,region
0,Balu shahi,"Maida flour, yogurt, oil, sugar",vegetarian,45.0,25.0,sweet,dessert,West Bengal,East
1,Boondi,"Gram flour, ghee, sugar",vegetarian,80.0,30.0,sweet,dessert,Rajasthan,West
2,Gajar ka halwa,"Carrots, milk, sugar, ghee, cashews, raisins",vegetarian,15.0,60.0,sweet,dessert,Punjab,North
3,Ghevar,"Flour, ghee, kewra, milk, clarified butter, su...",vegetarian,15.0,30.0,sweet,dessert,Rajasthan,West
4,Gulab jamun,"Milk powder, plain flour, baking powder, ghee,...",vegetarian,15.0,40.0,sweet,dessert,West Bengal,East
...,...,...,...,...,...,...,...,...,...
175,Prawn malai curry,"Coconut milk, prawns, garlic, turmeric, sugar",non vegetarian,15.0,50.0,spicy,main course,West Bengal,East
176,Shukto,"Green beans, bitter gourd, ridge gourd, banana...",vegetarian,10.0,20.0,spicy,main course,West Bengal,East
177,Til Pitha,"Glutinous rice, black sesame seeds, gur",vegetarian,5.0,30.0,sweet,dessert,Assam,North East
178,Bebinca,"Coconut milk, egg yolks, clarified butter, all...",vegetarian,20.0,60.0,sweet,dessert,Goa,West
179,Mawa Bati,"Milk powder, dry fruits, arrowroot powder, all...",vegetarian,20.0,45.0,sweet,dessert,Madhya Pradesh,Central

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
قسمت اول
</font>
</h2>
<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
بسیار شنیده‌ایم که هندوها عاشق غذاهای تند هستند! حال می‌خواهیم با توجه به مجموعه‌داده‌ی موجود صحت این گزاره را بررسی کرده و ببینیم که چه نسبتی از کل غذاهای این مجموعه، دارای مزه‌ی تندی هستند؟
برای این کار کافیست حاصل تقسیم تعداد غذاهای تند مزه را بر تعداد کل غذاها حساب کنید و در متغیر <code>spicy_ratio</code> ذخیره کنید.
</font>
</p>

In [ ]:
spicy_ratio = np.mean(df['flavor_profile'].apply(lambda x: x == 'spicy'))
spicy_ratio

np.float64(0.5666666666666667)

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
قسمت دوم
</font>
</h2>
<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
اکنون می‌خواهیم بدانیم کدام غذاها از لحظه‌ی شروع آماده‌سازی مخلفات تا لحظه‌ی آماده‌ی سرو شدن، بیشترین زمان را مصرف می‌کنند.
برای این‌کار باید جمع مدت زمان آماده‌سازی و زمان لازم برای طبخ غذا و همچنین نام غذا را در نظر گرفته و سپس به نوبت، اول <b>به‌ترتیب نزولی</b>  جمع مدت زمان آماده‌سازی و طبخ غذا و سپس <b>به‌ترتیب صعودی</b> نام غذا، داده را مرتب کنید و <b>۱۰ غذایی</b> که بیشترین زمان را مصرف می‌کنند(۱۰ ردیف اول) را در قالب یک دیتافریم در متغیر <code>df_most_time_consuming</code> ذخیره کنید.


</font>
</p>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
<span style="color:#0099cc"><b>نکته:</b></span>
    فرمت و ترتیب ستون‌های دیتافریم <code>df_most_time_consuming</code> باید دقیقاً شبیه به دیتافریم <code>df</code> باشد. یعنی این دیتافریم دارای ۱۰ سطر و ۹ ستون خواهد بود.
</font>
</p>

In [ ]:
df['total_time'] = df['prep_time'] + df['cook_time']

In [ ]:
df = df.sort_values(by=['total_time', 'name'], ascending=[False, True])

In [ ]:
df.head(10)

,name,ingredients,diet,prep_time,cook_time,flavor_profile,course,state,region,total_time
56,Shrikhand,"Curd, sugar, saffron, cardamom",vegetarian,10.0,720.0,sweet,dessert,Maharashtra,West,730.0
99,Pindi chana,"Fennel, tea bags, tomato, kasuri methi, cinnamon",vegetarian,500.0,120.0,spicy,main course,Punjab,North,620.0
23,Misti doi,"Milk, jaggery",vegetarian,480.0,30.0,sweet,dessert,West Bengal,East,510.0
42,Poornalu,"Chana dal, jaggery",vegetarian,240.0,60.0,sweet,dessert,Andhra Pradesh,South,300.0
59,Chak Hao Kheer,"Rice, milk, sugar, cardamom",vegetarian,240.0,45.0,sweet,dessert,Manipur,North East,285.0
104,Tandoori Chicken,"Greek yogurt, garam masala, kasuri methi, mari...",non vegetarian,240.0,30.0,spicy,main course,Punjab,North,270.0
105,Tandoori Fish Tikka,"Chickpea flour, biryani masala powder, yogurt,...",non vegetarian,240.0,30.0,spicy,starter,Punjab,North,270.0
40,Obbattu holige,"Maida flour, turmeric, coconut, chickpeas, jag...",vegetarian,180.0,60.0,sweet,main course,Karnataka,South,240.0
27,Ras malai,"Chhena, reduced milk, pistachio",vegetarian,180.0,60.0,sweet,dessert,West Bengal,East,240.0
106,Attu,"Whole wheat flour, arhar dal, ginger, kala jee...",vegetarian,150.0,25.0,spicy,snack,Andhra Pradesh,South,175.0

In [ ]:
del df['total_time']

In [ ]:
df_most_time_consuming = df.head(10)
df_most_time_consuming

,name,ingredients,diet,prep_time,cook_time,flavor_profile,course,state,region
56,Shrikhand,"Curd, sugar, saffron, cardamom",vegetarian,10.0,720.0,sweet,dessert,Maharashtra,West
99,Pindi chana,"Fennel, tea bags, tomato, kasuri methi, cinnamon",vegetarian,500.0,120.0,spicy,main course,Punjab,North
23,Misti doi,"Milk, jaggery",vegetarian,480.0,30.0,sweet,dessert,West Bengal,East
42,Poornalu,"Chana dal, jaggery",vegetarian,240.0,60.0,sweet,dessert,Andhra Pradesh,South
59,Chak Hao Kheer,"Rice, milk, sugar, cardamom",vegetarian,240.0,45.0,sweet,dessert,Manipur,North East
104,Tandoori Chicken,"Greek yogurt, garam masala, kasuri methi, mari...",non vegetarian,240.0,30.0,spicy,main course,Punjab,North
105,Tandoori Fish Tikka,"Chickpea flour, biryani masala powder, yogurt,...",non vegetarian,240.0,30.0,spicy,starter,Punjab,North
40,Obbattu holige,"Maida flour, turmeric, coconut, chickpeas, jag...",vegetarian,180.0,60.0,sweet,main course,Karnataka,South
27,Ras malai,"Chhena, reduced milk, pistachio",vegetarian,180.0,60.0,sweet,dessert,West Bengal,East
106,Attu,"Whole wheat flour, arhar dal, ginger, kala jee...",vegetarian,150.0,25.0,spicy,snack,Andhra Pradesh,South

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
<b>سلول جواب‌ساز</b>
</font>
</h2>


<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
    برای ساخته‌شدن فایل <code>result.zip</code> سلول زیر را اجرا کنید. توجه داشته باشید که پیش از اجرای سلول زیر تغییرات اعمال شده در نت‌بوک را ذخیره کرده باشید (<code>ctrl+s</code>) تا در صورت نیاز به پشتیبانی امکان بررسی کد شما وجود داشته باشد.
</font>
</p>

In [ ]:
import zipfile

np.save("spicy_ratio", np.array(spicy_ratio))
df_most_time_consuming.to_csv('df_most_time_consuming.csv', index=False)

def compress(file_names):
    print("File Paths:")
    print(file_names)
    compression = zipfile.ZIP_DEFLATED
    with zipfile.ZipFile("result.zip", mode="w") as zf:
        for file_name in file_names:
            zf.write('./' + file_name, file_name, compress_type=compression)

file_names = ["spicy_ratio.npy", "df_most_time_consuming.csv", "hindustan.ipynb"]
compress(file_names)

File Paths:
['spicy_ratio.npy', 'df_most_time_consuming.csv', 'hindustan.ipynb']