<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
دوچرخه‌سواران بی‌طاقت
</font>
</h1>
<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
دوچرخه‌سوران خیلی روی دما حساس هستند. دمایی که دوچرخه‌سواران احساس می‌کنند معمولاً با سرعت باد و رطوبت هوا رابطه دارد. در این تمرین می‌خواهیم با توجه به مجموعه‌داده‌ی دمای روزهای مختلف، به یک کسب‌و‌کار اجاره‌ی دوچرخه کمک کنیم تا در روزهای مختلف و در دماهای مختلف دوچرخه‌های بیشتری اجاره دهد.   
</font>
</p>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os
os.chdir('/content/drive/MyDrive/ML/DataMining')

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
مجموعه‌داده
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
با اجرای سلول زیر می‌توانید داده‌های این تمرین را به‌شکل یک دیتافریم بخوانید. این مجموعه‌داده شامل ستون‌های زیر است:
</font>
</p>


<center>
<div dir=rtl style="direction: rtl;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>

| <b>ستون</b> | <b>توضیحات</b> |
| :---: | :---: |
| <code>cnt</code> | تعداد دوچرخه‌های اجاره داده‌شده در روز |
| <code>t1</code> | دمای واقعی اندازه‌گیری‌شده در آن روز |
| <code>t2</code> | میانگین دمایی که دوچرخه‌سواران احساس کرده‌اند |
| <code>humidity</code> | رطوبت هوا در آن روز |
| <code>wind_speed</code> | سرعت باد در آن روز |
|‌ <code>is_weekend</code> | آیا آن روز،‌ روز غیرکاری (آخر هفته) هست یا خیر |
| <code>season</code> | چندمین فصل سال |

</font>
</div>
</center>

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('/content/drive/MyDrive/ML/DataMining/دوچرخه سواران بی طاقت/bikes_borrowed.csv')
df.head()

   cnt   t1   t2  humidity  wind_speed  is_weekend  season
0  182  3.0  2.0      93.0         6.0         1.0     3.0
1  138  3.0  2.5      93.0         5.0         1.0     3.0
2  134  2.5  2.5      96.5         0.0         1.0     3.0
3   72  2.0  2.0     100.0         0.0         1.0     3.0
4   47  2.0  0.0      93.0         6.5         1.0     3.0

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    نحوه‌ی کار با تابع <code>read_csv</code> را در درسنامه‌های آینده یاد می‌گیرید؛ اما به استفاده از <code>head</code> در این کد دقت کنید؛ همان‌طور که گفتیم، این تابع به‌طور پیش‌فرض، ۵ داده‌ی بالای دیتافریم را به ما نشان می‌دهد.
</font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
قسمت اول
    </font>
</h2>


<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    همان‌طور که می‌بینید نام ستون‌های <code>t1</code> و <code>t2</code> خیلی کلی است و بیانگر معنای مقدار آن‌ها نیست، به همین دلیل خوب است تا نام آن‌ها را تغییر دهیم.
<br>
    در سلول زیر، نام ستون <code>t1</code> را به <code>t_real</code> و نام ستون <code>t2</code> را به <code>t_feels_like</code> تغییر دهید.
<br>
    برای تغییر نام نمایه‌ها یا ستون‌ها می‌توانیم همچون کد زیر از تابع <code>rename</code> استفاده کنیم:
<br>
</font>
</p>

```python
df.rename(columns={"col1": "new_col1", "col2": "new_col2"} , inplace = True)
```

In [ ]:
df.rename(columns={"t1":"t_real","t2":"t_feels_like"}, inplace = True)

df.head()

   cnt  t_real  t_feels_like  humidity  wind_speed  is_weekend  season
0  182     3.0           2.0      93.0         6.0         1.0     3.0
1  138     3.0           2.5      93.0         5.0         1.0     3.0
2  134     2.5           2.5      96.5         0.0         1.0     3.0
3   72     2.0           2.0     100.0         0.0         1.0     3.0
4   47     2.0           0.0      93.0         6.5         1.0     3.0

In [ ]:
df.shape

(17414, 7)

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    به پارامتر <code>inplace = True</code> دقت کنید؛ وجود این پارامتر باعث می‌شود که تابع <code>rename</code>، به‌جای آن‌که یک کپی از دیتافریم تهیه کرده و بعد از اعمال تغییرات آن کپی را خروجی دهد، تغییرات را مستقیماً روی دیتافریم اصلی اعمال کند.
<br>
برای درک بهتر این موضوع می‌توانید یک‌بار این پارامتر را حذف کرده و سپس مجدد <code dir=ltr>df.head()</code> را خروجی بگیرید و بررسی کنید که آیا نام ستون‌ها تغییر کرده است یا خیر؟
</font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
قسمت دوم
    </font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
از آن‌جایی که اغلب روز‌هایی که دوچرخه‌سواران از هوا گلایه دارند روز‌های بادی است، تصمیم گرفتیم که محاسبات را فقط برای روز‌هایی که سرعت باد بیشتر از ۱۰ است انجام دهیم.
<br>
    بنابراین در دیتافریم <code>windy_days_df</code>، تنها داده‌هایی را ذخیره کنید که سرعت باد آن‌ها بیشتر از ۱۰ باشد (خود ۱۰ را در نظر نگیرید).
</font>
</p>

In [ ]:
windy_days_df = df.loc[df['wind_speed'] > 10]

windy_days_df.head()

    cnt  t_real  t_feels_like  humidity  wind_speed  is_weekend  season
10  528     3.0          -0.5      93.0        12.0         1.0     3.0
11  727     2.0          -1.5     100.0        12.0         1.0     3.0
12  862     2.0          -1.5      96.5        13.0         1.0     3.0
13  916     3.0          -0.5      87.0        15.0         1.0     3.0
15  869     2.0          -1.5      93.0        11.0         1.0     3.0

In [ ]:
windy_days_df.shape

(12595, 7)

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
قسمت سوم
    </font>
</h2>


<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
برای انجام باقی محاسبات فقط ستون‌های مخصوص دما را نیاز داریم؛ پس برای دیتافریم <code>windy_days_df</code>، ستون‌های <code>humidity</code> , <code>t_feels_like</code> , <code>t_real</code> و <code>wind_speed</code>را ذخیره کرده (از دیتافریم <code>windy_days_df</code>) و باقی ستون‌ها را نادیده بگیرید.

</font>
</p>

In [ ]:
windy_days_df = windy_days_df.drop(['cnt', 'is_weekend', 'season'], axis=1)

windy_days_df.head()

    t_real  t_feels_like  humidity  wind_speed
10     3.0          -0.5      93.0        12.0
11     2.0          -1.5     100.0        12.0
12     2.0          -1.5      96.5        13.0
13     3.0          -0.5      87.0        15.0
15     2.0          -1.5      93.0        11.0

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
در مراحل بعدی می‌خواهیم برخی مقادیر دیتافریم را تغییر دهیم پس برای آن‌که دیتافریم اصلی و <code>windy_days_df</code> تغییر نکنند لازم است تا از تابع <code>copy</code> استفاده کنیم.
<br>
به‌طور کلی استفاده از عملگر مساوی برای دیتافریم‌ها در پانداز مانند نامپای عمل می‌کنند و تنها یک اشاره‌گر (pointer) جدید به همان دیتافریم اضافه می‌شود. بنابراین، تغییر دادن هر کدام از دیتافریم‌ها باعث تغییر دیگری نیز می‌شود.
<br>
    استفاده از تابع <code>copy</code> این قابلیت را برای ما ایجاد می‌کند که یک کپی از دیتافریم اولیه دریافت کنیم و تغییر یکی تاثیری روی دیگری نداشته باشد.
<br>
در ادامه بیشتر  این ویژگی را بررسی می‌کنیم اما فعلاً کافیست سلول زیر را اجرا کنید.
</font>
</p>

In [ ]:
temperature_df = windy_days_df.copy()

In [ ]:
temperature_df

       t_real  t_feels_like  humidity  wind_speed
10        3.0          -0.5      93.0        12.0
11        2.0          -1.5     100.0        12.0
12        2.0          -1.5      96.5        13.0
13        3.0          -0.5      87.0        15.0
15        2.0          -1.5      93.0        11.0
...       ...           ...       ...         ...
17409     5.0           1.0      81.0        19.0
17410     5.0           1.0      81.0        21.0
17411     5.5           1.5      78.5        24.0
17412     5.5           1.5      76.0        23.0
17413     5.0           1.0      76.0        22.0

[12595 rows x 4 columns]

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
قسمت چهارم
    </font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
برای انجام تحلیل‌های بهتر نیاز داریم بدانیم که یک روز نسبت به بازه‌ی کلی دما تا چه‌اندازه گرم است. برای این کار به‌ترتیب مراحل زیر را انجام دهید:
<br>
    ۱- در متغیر <code>t_max</code> مقدار ماکزیمم ستون <code>t_real</code> را ذخیره کنید.
<br>
    ۲- در متغیر <code>t_min</code> مقدار مینیمم ستون <code>t_real</code> را ذخیره کنید.
<br>
۳- ستون جدیدی به نام <code>t_percent</code> به دیتافریم اضافه کنید. در این ستون از فرمول زیر برای نرمال‌سازی و پیدا کردن دمای نسبی استفاده کنید.
<br>
</font>
</p>

```python
((temp - min) / (max - min)) * 100
```

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
<span style="color:green"><b>راهنمایی:</b></span>
 تمام عملیات این مرحله را می‌توانید با توابع نامپای انجام دهید. همان‌طور که گفتیم پانداز بر اساس نامپای نوشته شده، پس تمامی عملیات‌های نامپای در این‌جا هم قابل استفاده است.
</font>
</p>

In [ ]:
# find maximum value of t_real column
t_max = temperature_df['t_real'].max()

# find minimum value of t_real column
t_min = temperature_df['t_real'].min()

temperature_df['t_percent'] = ((temperature_df['t_real'] - t_min) / (t_max - t_min)) * 100

temperature_df.head()

    t_real  t_feels_like  humidity  wind_speed  t_percent
10     3.0          -0.5      93.0        12.0  11.428571
11     2.0          -1.5     100.0        12.0   8.571429
12     2.0          -1.5      96.5        13.0   8.571429
13     3.0          -0.5      87.0        15.0  11.428571
15     2.0          -1.5      93.0        11.0   8.571429

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
قسمت پنجم
    </font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
حال می‌خواهیم دمایی که احساس می‌شود را طبق اطلاعات موجود پیش‌بینی کرده و مقادیر این ستون (<code>t_feels_like</code>) را جایگزین کنیم.
برای مقداردهی این ستون از فرمول زیر استفاده کنید:
<br>
</font>
</p>

$$
t\_feels\_like = t\_real + (humidity * t\_real)/1000 - (wind\_speed)/10 -2
$$
<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    <span style="color:orange"><b>یادآوری:</b></span>
 هر ستون دیتافریم را می‌توانید مانند یک سری جدا کرده و مانند یک آرایه‌ی نامپای با آن رفتار کنید.
</font>
</p>

In [ ]:
temperature_df['t_feels_like'] = temperature_df['t_real'] + (temperature_df['humidity'] * temperature_df['t_real']) / 1000 - temperature_df['wind_speed'] / 10 - 2

temperature_df.head()

    t_real  t_feels_like  humidity  wind_speed  t_percent
10     3.0         0.079      93.0        12.0  11.428571
11     2.0        -1.000     100.0        12.0   8.571429
12     2.0        -1.107      96.5        13.0   8.571429
13     3.0        -0.239      87.0        15.0  11.428571
15     2.0        -0.914      93.0        11.0   8.571429

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    همان‌طور که می‌بینید مقدار ستون <code>t_feels_like</code> تغییر کرده و دیگر مانند آن‌چه در دیتافریم اولیه داشتیم نیست. حال بیایید کارکرد تابع ‍<code>copy</code> را بررسی کنیم. اگر تمام مراحل را درست پیش رفته باشید، مقدار ستون <code>t_feels_like</code> در دیتافریم ‍‍<code>windy_days_df</code> نباید تغییر کرده باشد. برای اطمینان از این موضوع با استفاده از تابع <code>head</code> می‌توانیم مقادیر این دو دیتافریم را مقایسه کنیم.

</font>
</p>

In [ ]:
windy_days_df.head()

    t_real  t_feels_like  humidity  wind_speed
10     3.0          -0.5      93.0        12.0
11     2.0          -1.5     100.0        12.0
12     2.0          -1.5      96.5        13.0
13     3.0          -0.5      87.0        15.0
15     2.0          -1.5      93.0        11.0

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
قسمت ششم
    </font>
</h2>



<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
در نهایت می‌خواهیم دقت این پیش‌بینی را محاسبه کنیم. برای این کار از فرمول زیر استفاده می‌کنیم که با نام <a href="https://en.wikipedia.org/wiki/Mean_absolute_error"><i>Mean Absolute Error</i> یا <i>MAE</i></a> شناخته می‌شود.
<br>
</font>
</p>


$$
\text{MAE} = \frac{1}{n} \sum_{i=1}^{n} | y_i - \hat{y}_i |
$$

<br>
<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
برای محاسبه این مقدار می‌توانیم از توابع <a href="https://numpy.org/doc/stable/reference/generated/numpy.mean.html"><code>()np.abs</code></a> و <a href="https://numpy.org/devdocs/reference/generated/numpy.absolute.html"><code>()np.mean</code></a> استفاده کنیم.
<br>
</font>
</p>

$$
\text{diffrence} = mean( | t\_feels\_like _{temperature\_df} - t\_feels\_like_{windy\_days\_df} | )
$$

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
این مقدار را محاسبه و در متغیر <code>diffrence</code> ذخیره کنید.
</font>
</p>

In [ ]:
diffrence = np.mean(np.abs(temperature_df['t_feels_like'] - windy_days_df['t_feels_like']))
print(diffrence)

2.028340505491597

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
قسمت هفتم
    </font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    در این تمرین با تابع <code>head(n)</code> کار کردیم اما بیایید به بررسی عمیق‌تر این تابع بپردازیم.
<br>
به‌طور کلی این تابع تنها برای نمایش داده‌ها استفاده نمی‌شود، بلکه اعمال آن روی دیتافریم یک کپی از <code>n</code> داده‌ی اول آن را برمی‌گرداند و می‌توان آن را در دیتافریم جداگانه‌ای ذخیره کرد.
<br>
    در دیتافریم زیر، ۱۰۰ داده‌ی اول دیتافریم <code>temperature_df</code> را ذخیره کنید.
</font>
</p>

In [ ]:
final_df = temperature_df.head(100)
final_df

     t_real  t_feels_like  humidity  wind_speed  t_percent
10      3.0        0.0790      93.0        12.0  11.428571
11      2.0       -1.0000     100.0        12.0   8.571429
12      2.0       -1.1070      96.5        13.0   8.571429
13      3.0       -0.2390      87.0        15.0  11.428571
15      2.0       -0.9140      93.0        11.0   8.571429
..      ...           ...       ...         ...        ...
136    13.5        9.1475      85.0        35.0  41.428571
137    15.0       10.6300      82.0        36.0  45.714286
138    15.5       10.5935      77.0        41.0  47.142857
139    15.0        9.6800      72.0        44.0  45.714286
140    15.0        9.9200      68.0        41.0  45.714286

[100 rows x 5 columns]

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
<b>سلول جواب‌ساز</b>
</font>
</h2>


<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
    برای ساخته‌شدن فایل <code>result.zip</code> سلول زیر را اجرا کنید. توجه داشته باشید که پیش از اجرای سلول زیر تغییرات اعمال شده در نت‌بوک را ذخیره کرده باشید (<code>ctrl+s</code>) تا در صورت نیاز به پشتیبانی امکان بررسی کد شما وجود داشته باشد.
</font>
</p>

In [ ]:
import zlib
import zipfile

np.savez("answers.npz", diffrence=diffrence, t_min=t_min , t_max=t_max)
df.to_csv('bikes.csv', index=True)
windy_days_df.to_csv('windy_days.csv', index=True)
temperature_df.to_csv("temperature.csv", index=True)
final_df.to_csv("final.csv", index=True)

def compress(file_names):
    print("File Paths:")
    print(file_names)
    compression = zipfile.ZIP_DEFLATED
    with zipfile.ZipFile("result.zip", mode="w") as zf:
        for file_name in file_names:
            zf.write('./' + file_name, file_name, compress_type=compression)

file_names = ["bikes.csv", "windy_days.csv", "temperature.csv",
              "final.csv", "answers.npz" , "mad_cyclists.ipynb"]
compress(file_names)

File Paths:
['bikes.csv', 'windy_days.csv', 'temperature.csv', 'final.csv', 'answers.npz', 'mad_cyclists.ipynb']