<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
    شاخگرام
</font>
</h1>

<div dir=rtl id="start" style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
	<font face="vazirmatn" size=3>
در درسنامه‌های پیشین با ساختمان‌داده‌های پرکاربرد در پانداز آشنا شدیم. در این تمرین، قصد داریم انتخاب داده از یک دیتافریم را بیشتر تمرین کنیم.
مجموعه‌داده‌ای که برای این تمرین در دست داریم، مربوط به یک شبکه‌ی اجتماعی فرضی به نام شاخگرام است که در آن افراد سعی می‌کنند هرچه بیشتر شاخ شوند!
 هدف اصلی این تمرین بررسی داده‌های شاخگرام و نوشتن شرط‌های گوناگون جهت فیلتر کردن شاخ‌های سطوح مختلف است.
    </font>
</div>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os
os.chdir('/content/drive/MyDrive/ML/DataMining')

In [ ]:
import pandas as pd
import numpy as np

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
مجموعه‌داده
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
داده‌های مربوط به این تمرین در فایل <code>shakhgram.csv</code> قرار گرفته و به کمک سلول زیر می‌توانید آن را به شکل یک دیتافریم بخوانید و در متغیر <code>df</code> ذخیره کنید. این دیتافریم شامل ستون‌های زیر است:
</font>
</p>

<center>
<div dir=rtl style="direction: rtl;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>

| نام ستون | توضیحات |
| :---: | :---: |
| `owner_name` | اسم صاحب پیج |
| `follower` | تعداد دنبال‌کنندگان پیج |
| `following` | تعداد دنبال‌شوندگان پیج |
| `post_number` | تعداد پست‌های پیج |

</font>
</div>
</center>

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/ML/DataMining/شاخگرام/shakhgram.csv")

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
    مشاهده‌ی داده‌ها
    </font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
با اجرای سلول زیر، ۵ سطر اول دیتافریم نمایش داده می‌شود تا یک نگاه کلی به داده‌ها داشته باشیم.
پیشنهاد می‌کنیم سعی کنید ستون‌ها و سطرهای مختلفی از دیتافریم را انتخاب و مشاهده کنید تا علاوه بر این‌که با مجموعه‌داده بیشتر آشنا می‌شوید، برای پیاده‌سازی پاسخ تمرین نیز آماده‌تر شوید!
</font>
</p>

In [ ]:
df.head()

          owner_name     follower  following  post_number
0  Muhammad Schaefer  108751787.0       45.0         61.0
1          Ezra Kemp  172731383.0       71.0         43.0
2           Eli Good  105194939.0       20.0         44.0
3   Lillianna Pruitt   14807976.0       11.0         88.0
4    Carlie Woodward  228517005.0       68.0         52.0

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
    قسمت اول
    </font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    در این شبکه‌ی اجتماعی، ۵ دسته از شاخ‌بودن وجود دارد. برای این‌که عضو هر دسته باشیم، می‌بایست پیج و اسم ما شرایط خاصی داشته باشد.
    <br>
    اولین دسته‌ از شاخ‌های شاخگرام، شاخ‌های برنجی هستند؛ شاخ‌های برنجی،  افرادی هستند که تعداد افرادی که توسط پیج‌شان دنبال می‌شوند (<code>following</code>) <b>از ۱۱ کمتر</b> باشد.
    <br>
    در سلول زیر، بخشی از دیتافریم اصلی را که شرایط شاخ‌های برنجی دارند جدا کرده و در متغیر <code>berenji_df</code> ذخیره کنید.
</font>
</p>

In [ ]:
berenji_df = df.loc[lambda x: x["following"] < 11]
berenji_df

        owner_name     follower  following  post_number
55  Dexter Salazar  265575683.0       10.0         54.0
71     Eden Walter   50414607.0       10.0         82.0

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
    قسمت دوم
    </font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    در متغیر <code>mesi_df</code>، شاخ‌های مسی را ذخیره کنید؛ شاخ‌های مسی، افرادی هستند که تعداد پست‌های پیج‌شان از تعداد افرادی که آن پیج دنبال‌شان می‌کند (<code>following</code>) بیشتر باشد.
</font>
</p>

In [ ]:
mesi_df = df.loc[lambda x: x["following"] < x["post_number"]]
mesi_df

            owner_name     follower  following  post_number
0    Muhammad Schaefer  108751787.0       45.0         61.0
2             Eli Good  105194939.0       20.0         44.0
3     Lillianna Pruitt   14807976.0       11.0         88.0
6      Abbey Patterson  117816608.0       65.0         98.0
8        Teagan Newman  145440825.0       39.0         85.0
9     Bianca Velazquez  184433225.0       72.0         91.0
10         Emely Olsen  197123487.0       43.0         58.0
12       Ivan Randolph  233996265.0       31.0         45.0
13      Priscilla Shea   23888252.0       69.0         72.0
14         Ryan Berger  107802883.0       85.0         91.0
16      Kira Castaneda  246047852.0       12.0         63.0
17   Kadence Henderson   77927317.0       53.0         57.0
18      Timothy Fowler  224887843.0       50.0         73.0
19      Precious Ramos   48236154.0       34.0         76.0
24     Charles Morales  222955873.0       12.0         38.0
27    Hailee Armstrong  313687859.0       55.0         94.0
29     Gabriel Calhoun  132769603.0       16.0         58.0
39      Harper Hensley  224837846.0       57.0         59.0
40         Alexia Moss  314936599.0       17.0         48.0
41        Boston Stout  293331811.0       13.0         56.0
43        Khalil Bryan  279582669.0       48.0         84.0
44      Jakobe Schultz  136273816.0       34.0         82.0
47       Zachery Keith   34037577.0       47.0         49.0
49  Yasmine Hutchinson  181380421.0       13.0         98.0
50        Marlee Moyer  224912384.0       36.0         95.0
52        Mylie Prince  172675476.0       18.0         43.0
54    Esmeralda Henson  240302137.0       65.0         96.0
55      Dexter Salazar  265575683.0       10.0         54.0
56         Jamie Oneal  252094671.0       12.0         41.0
59        Corey Hansen   10389852.0       28.0         63.0
62      Lilah Whitaker   95378667.0       31.0         49.0
64       Britney James  161446658.0       41.0         93.0
71         Eden Walter   50414607.0       10.0         82.0
78          Kian Hanna   79265883.0       21.0         24.0
79      Claire Salinas  239596097.0       49.0         66.0
81          Harper Day  151388804.0       34.0         59.0
82         Hope Becker   68662078.0       28.0         83.0
86       Nasir Mcgrath  107737269.0       12.0         99.0
87       Blaine Greene   17519059.0       83.0         88.0
88        Janet Knight  137375221.0       18.0         26.0
89        Lana Hensley  151213150.0       49.0         80.0
90     Destiney Orozco  250085334.0       61.0         72.0
92      Leslie Salinas  276001851.0       65.0         89.0
94      Reyna Copeland  214443881.0       44.0         89.0
99          Ezra Booth  296470673.0       49.0         89.0

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
    قسمت سوم
    </font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    در متغیر <code>boronzi_df</code>، شاخ‌های برنزی را ذخیره کنید؛
    شاخ‌های برنزی، افرادی هستند که تعداد دنبال‌کنندگان (<code>follower</code>) پیج‌شان بیشتر از یک میلیون نفر باشد.
</font>
</p>

In [ ]:
boronzi_df = df.loc[lambda x: x["follower"] > 1000000]
boronzi_df

           owner_name     follower  following  post_number
0   Muhammad Schaefer  108751787.0       45.0         61.0
1           Ezra Kemp  172731383.0       71.0         43.0
2            Eli Good  105194939.0       20.0         44.0
3    Lillianna Pruitt   14807976.0       11.0         88.0
4     Carlie Woodward  228517005.0       68.0         52.0
..                ...          ...        ...          ...
95      Alaina Cortez  206571647.0       83.0         82.0
96         Aiyana Orr  246069137.0       85.0         44.0
97        Damien Mack  175172516.0       84.0         58.0
98    Santino Shelton  103682240.0       86.0         71.0
99         Ezra Booth  296470673.0       49.0         89.0

[100 rows x 4 columns]

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
    قسمت چهارم
    </font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    در متغیر <code>noghreyee_df</code>، شاخ‌های نقره‌ای را ذخیره کنید؛ شاخ‌های نقره‌ای،‌ افرادی هستند که دو شرط زیر همزمان برای آن‌ها برقرار باشد:
    <ol dir=rtl>
        <li>تعداد دنبال‌کنندگان (<code>follower</code>) پیج‌شان بزرگ‌تر یا مساوی ۱۰ میلیون باشد.</li>
        <li>تعداد دنبال‌شوندگان توسط پیج (<code>following</code>) کم‌تر از ۵۰ باشد.</li>
    </ol>
</font>
</p>

In [ ]:
noghreyee_df = df.loc[lambda x: (x["follower"] >= 10000000) & (x["following"] < 50)]
noghreyee_df

            owner_name     follower  following  post_number
0    Muhammad Schaefer  108751787.0       45.0         61.0
2             Eli Good  105194939.0       20.0         44.0
3     Lillianna Pruitt   14807976.0       11.0         88.0
8        Teagan Newman  145440825.0       39.0         85.0
10         Emely Olsen  197123487.0       43.0         58.0
12       Ivan Randolph  233996265.0       31.0         45.0
16      Kira Castaneda  246047852.0       12.0         63.0
19      Precious Ramos   48236154.0       34.0         76.0
24     Charles Morales  222955873.0       12.0         38.0
29     Gabriel Calhoun  132769603.0       16.0         58.0
31          Ivy Fields  234324677.0       49.0         22.0
32        Jaime Stuart   71774373.0       48.0         44.0
36     Demarion Suarez   63641416.0       12.0         11.0
40         Alexia Moss  314936599.0       17.0         48.0
41        Boston Stout  293331811.0       13.0         56.0
42    Chasity Cisneros  303490848.0       48.0         36.0
43        Khalil Bryan  279582669.0       48.0         84.0
44      Jakobe Schultz  136273816.0       34.0         82.0
47       Zachery Keith   34037577.0       47.0         49.0
49  Yasmine Hutchinson  181380421.0       13.0         98.0
50        Marlee Moyer  224912384.0       36.0         95.0
52        Mylie Prince  172675476.0       18.0         43.0
53         Raven Stone   82717282.0       48.0         16.0
55      Dexter Salazar  265575683.0       10.0         54.0
56         Jamie Oneal  252094671.0       12.0         41.0
59        Corey Hansen   10389852.0       28.0         63.0
60     Audrina Nichols  319228713.0       41.0         15.0
62      Lilah Whitaker   95378667.0       31.0         49.0
64       Britney James  161446658.0       41.0         93.0
71         Eden Walter   50414607.0       10.0         82.0
78          Kian Hanna   79265883.0       21.0         24.0
79      Claire Salinas  239596097.0       49.0         66.0
81          Harper Day  151388804.0       34.0         59.0
82         Hope Becker   68662078.0       28.0         83.0
83      Cameron Murphy  281439342.0       22.0         17.0
86       Nasir Mcgrath  107737269.0       12.0         99.0
88        Janet Knight  137375221.0       18.0         26.0
89        Lana Hensley  151213150.0       49.0         80.0
94      Reyna Copeland  214443881.0       44.0         89.0
99          Ezra Booth  296470673.0       49.0         89.0

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
    قسمت پنجم
    </font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
        در متغیر <code>talayee_df</code>، شاخ‌های طلایی را ذخیره کنید؛
شاخ‌های طلایی افرادی هستند که حداقل یکی از دو شرط زیر را داشته باشند (یعنی شرط اول یا شرط دوم)
<ol dir=rtl>
        <li>تعداد دنبال‌کنندگان (<code>follower</code>) پیج‌شان بزرگ‌تر از ۱۰ میلیون و تعداد دنبال‌شوندگان (<code>following</code>) آن‌ها کمتر از ۲۰ باشد.</li>
        <li>تعداد پست‌های‌شان کمتر از ۱۵ باشد و حرف <code>R</code> در اسم صاحب پیج وجود داشته باشد (مثل <code dir=ltr>!BooAzaR</code>).</li>
    </ol>
</font>
</p>

In [ ]:
talayee_df = df.loc[lambda x: ((x["follower"] >= 10000000) & (x["following"] < 20)) | ((x["post_number"] < 15) & (x["owner_name"].str.contains('R')))]
talayee_df

            owner_name     follower  following  post_number
3     Lillianna Pruitt   14807976.0       11.0         88.0
15          Hayden Roy  248522613.0       79.0         11.0
16      Kira Castaneda  246047852.0       12.0         63.0
24     Charles Morales  222955873.0       12.0         38.0
29     Gabriel Calhoun  132769603.0       16.0         58.0
36     Demarion Suarez   63641416.0       12.0         11.0
40         Alexia Moss  314936599.0       17.0         48.0
41        Boston Stout  293331811.0       13.0         56.0
49  Yasmine Hutchinson  181380421.0       13.0         98.0
52        Mylie Prince  172675476.0       18.0         43.0
55      Dexter Salazar  265575683.0       10.0         54.0
56         Jamie Oneal  252094671.0       12.0         41.0
71         Eden Walter   50414607.0       10.0         82.0
86       Nasir Mcgrath  107737269.0       12.0         99.0
88        Janet Knight  137375221.0       18.0         26.0

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
<b>سلول جواب‌ساز</b>
</font>
</h2>


<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
    برای ساخته‌شدن فایل <code>result.zip</code> سلول زیر را اجرا کنید. توجه داشته باشید که پیش از اجرای سلول زیر تغییرات اعمال شده در نت‌بوک را ذخیره کرده باشید (<code>ctrl+s</code>) تا در صورت نیاز به پشتیبانی امکان بررسی کد شما وجود داشته باشد.
</font>
</p>

In [ ]:
import zlib
import zipfile

berenji_df.to_csv('berenji.csv', index=True)
mesi_df.to_csv('mesi.csv', index=True)
boronzi_df.to_csv("boronzi.csv", index=True)
noghreyee_df.to_csv("noghreyee.csv", index=True)
talayee_df.to_csv("talayee.csv", index=True)

def compress(file_names):
    print("File Paths:")
    print(file_names)
    compression = zipfile.ZIP_DEFLATED
    with zipfile.ZipFile("result.zip", mode="w") as zf:
        for file_name in file_names:
            zf.write('./' + file_name, file_name, compress_type=compression)

file_names = ["berenji.csv", "mesi.csv", "boronzi.csv",
              "noghreyee.csv", "talayee.csv", "shakhgram.ipynb"]
compress(file_names)

File Paths:
['berenji.csv', 'mesi.csv', 'boronzi.csv', 'noghreyee.csv', 'talayee.csv', 'shakhgram.ipynb']